

INSERT INTO `abhi_question` (`que_id`, `que_desc`, `ans1`, `ans2`, `ans3`, `ans4`, `true_ans`, `subject`) VALUES
 ('1', 'What is the standard form of DOF?', 'a)   Degree of Finance', 'b)   Degree of Freedom', 'c)   Degree of Fail', 'd)   None of the above', 2, 'Manufacturing'),
 ('2', 'What is PPE?', 'Personal protective equipment ', 'Personal Product equipment ', 'Personal preventive equipment ', 'Personal private equipment ', 1, 'Manufacturing'),
 ('3', 'Who is responsible for Safety?', 'Everyone', 'Department Head', 'Individual ', 'Foreman', 3, 'Manufacturing'),
 ('4', 'What Customers needs?', 'Money', 'Failure', 'Help', 'Quality', 4, 'Manufacturing'),
 ('5', 'What defines Geometrical tolerance?', 'Shape', 'Numbers', 'Time', 'Points', 1, 'Manufacturing'),
 ('6', 'What is BOM?', 'Bill of manner', 'Bill of materials', 'Bill of mention', 'Bill of many', 2, 'Manufacturing'),
 ('7', 'Robot is derived from Czech word called?', 'Rabota', 'Robota', 'Rebota', 'Riboti', 2, 'Manufacturing'),
 ('8', 'How many types of Industrial Robots are there?', '5', '4', '1', '6', 4, 'Manufacturing'),
 ('9', 'What is the pay load capacity of Yaskawa AR1440?', '10kg', '11kg', '12kg', '13kg', 3, 'Manufacturing'),
 ('10', '"Which one of the following robots comes under first generation?', 'a)   Information robots', 'b)   Autonomous loading', 'c)   Autonomous harvesting', 'd)   None of the above', 2, 'Manufacturing'),
 ('11', 'How many axis does Yaskawa Robot have?', '4', '5', '6', '7', 3, 'Manufacturing'),
 ('12', '"What is the standard form of ZMP?', 'a)   Zero Memory Point', 'b)   Zero Momentum Point', 'c)   Zero Main Point', 'd)   None of the above', 2, 'Manufacturing'),
 ('13', 'How many laws are there in ROBOTICS?', '1', '2', '3', '4', 3, 'Manufacturing'),
 ('14', '"Which one of the following sections in robot manipulator used for positioning?', 'a)   Body & arm', 'b)   Wrist assembly', 'c)   Both a and b', 'd)   None of the above', 1, 'Manufacturing'),
 ('15', 'Which software is used for simulation in Yaskawa robots?', 'Motorun', 'Mototeach', 'Motoplay', 'Motosim', 4, , 'Manufacturing'),
 ('16', 'Which Robot can perform Pick and place?', 'Cartesian robot', 'Delta robot', 'Cylindrical Robot', 'Scara Robot', 2, 'Manufacturing'),
 ('17', 'What are production benefits of Robotics?', 'More time ', 'Low consistency', 'Better Quality', 'Slow Production', 3, 'Manufacturing'),
 ('18', 'What is the function of Teach mode?', 'Preparation and teaching of job', 'Autocycle of job', 'Playback of taught job', 'Callmaster job', 1, 'Manufacturing'),
 ('19', 'Which interpolation  is MOVJ?', 'Spline Interpolation', 'Circular Interpolation', 'Linear Interpolation', 'Joint Interpolation', 4, 'Manufacturing'),
 ('20', 'How many coordinate sysytem are available?', '6', '4', '3', '5', 2, 'Manufacturing'),
 ('21', 'What are Benefits of Robotic arc welding?', 'Quality', 'Risk', 'High maintenance', 'Less production', 1, 'Manufacturing'),
 ('22', 'Which type of welding are used in our workshop?', 'Tig welding', 'Resistance welding', 'Spot welding', 'Arc welding', 4, 'Manufacturing'),
 ('23', 'Time taken to deliver the product from order to dispatch?', 'Cycle time', 'Lead time', 'Delay time', 'Lean time', 2, 'Manufacturing'),
 ('24', 'The brain of the Industrial Robot  is?', 'Manipulator', 'Drive', 'Processor', 'End effector', 3, 'Manufacturing'),
 ('25', 'How many types of Conveyor systems are available?', '1', '2', '3', '4', 3, 'Manufacturing'),
 ('26', 'A robotic work cell is system composed of?', 'Lathe ', 'Robots and controller', 'Drilling machine', 'CNC machine', 2, 'Manufacturing'),
 ('27', 'Polar Robot is also called as', 'Spherical', 'Cylindrical', 'Scara ', 'Delta', 1, 'Manufacturing'),
 ('28', 'Two or more parts are fused together by means of heat is called?', 'Welding', 'Casting', 'Forging', 'Grinding', 1, 'Manufacturing'),
 ('29', 'The horizontal reach of material handling Robot of gp 12 is?', '1442mm', '1440mm', '1443mm', '1444mm', 2, 'Manufacturing'),
 ('30', 'What are the instructions used in  robotic Arc weldind process?', 'Arc ON and Arc OFF', 'Arc ON', 'Arc OFF', 'Arc RUN', 1, 'Manufacturing'),
 ('31', 'What is the Operating voltage of GP12?', '3Phase500V', '3Phase 200v', '3 Phase 100V', '3 Phase 230V', 4, 'Manufacturing'),
 ('32', 'What is the name of information sent from Robot sensor to  Robot Controllers?', 'Temperature', 'Feedback', 'Signal', 'Pressure', 2, 'Manufacturing'),
 ('33', 'The number of movable joints in  base,the arm and end effectors of Robot determines?', 'Degrees of freedom', 'Payload capacity', 'Operational limits', 'Flexibility', 1, 'Manufacturing'),
 ('34', 'The Digitization and Automation of Manufacturing is Related to?', 'Industry 1.0', 'Industry 2.0', 'Industry 3.0', 'Industry 4.0', 4, 'Manufacturing'),
 ('35', 'How many prismatic joints does cartesian Robot have?', '1', '2', '3', '4', 3, 'Manufacturing'),
 ('36', 'Which part of Industrial Robot is called as engine or motor?', 'Drive', 'End effector', 'Controller', 'Sensor', 3, 'Manufacturing'),
 ('37', 'Which of the following is an Electrical hazards?', 'Vibration', 'Release of Tool', 'Human Interaction', 'Arc Flash', 4, 'Manufacturing'),
 ('38', 'T C P Full form in Robotics is', 'Tool center point ', 'Tool center pitch', 'Tool center power', 'Tool centre program', 1, 'Manufacturing'),
 ('39', 'Which of the following checkpoint is used to monitor Robotic work cell?', 'Civil', 'Electrical and Mechanical', 'Chemical', 'Computer Science ', 2, 'Manufacturing'),
 ('40', 'What is the function of Gripper?', 'Welding', 'Holding', 'Grinding', 'Machining', 2, 'Manufacturing'),
 ('41', 'How welding defects are identified?', 'Heating', 'Touching', 'Smelling', 'Visual', 4, 'Manufacturing'),
 ('42', 'When is Rework done in welding?', 'Before welding', 'During welding', 'After Welding', 'During preparartion', 3, 'Manufacturing'),
 ('43', 'How to take care of Robotic cell?', 'Maintenance activities', 'Over production', 'undefined jobs', 'Utilizing raw material', 1, 'Manufacturing'),
 ('44', 'Which of the following raw material is used in arc welding?', 'Wood', 'Rubber', 'Polymer', 'Welding gas', 4, 'Manufacturing'),
 ('45', 'Vernier caliper is used in arc welding to measure?', 'Pressure', 'Thickness', 'Volume', 'Density', 2, 'Manufacturing'),
 ('46', 'Arc glare shields in Robotic welding is used to protect?', 'Eyes', 'Nose', 'Mouth', 'Head', 1, 'Manufacturing'),
 ('47', 'What is the capacity of yaskawa transformer in robotic cell?', '1KVA', '2KVA', '3KVA', '4KVA', 4, 'Manufacturing'),
 ('48', 'Which device is used to move materials from one location to another?', 'Transformer ', 'Teach Pendant ', 'Conveyor', 'Controller', 3, 'Manufacturing'),
 ('49', 'Which conveyor system are used to transport heavy unit loads?', 'Belt Conveyor', 'Chain Conveyor', 'Roller Conveyor', 'V-belt Conveyor', 2, 'Manufacturing'),
  ('50', 'Thermistor sensor are used to measure', 'Temperature', 'Pressure', 'Torque', 'Density', 1, 'Manufacturing')