

INSERT INTO `abhi_question` (`que_id`, `que_desc`, `ans1`, `ans2`, `ans3`, `ans4`, `true_ans`, `subject`) VALUES
('1', 'If you wanted to convey the most severe type of hazard, which word would you use?', 'Warning', 'Notice', 'Danger', 'Caution', 3, 'Artisan'),
('2', 'What is the class of fire caused by fire wood, paper, cloth?', 'Class ‘A’ fire', 'Class ‘B’ fire', 'Class ‘C’ fire', 'Class ‘D’ fire', 1, 'Artisan'),
('3', 'Which comes under mechanical occupational hazards?', 'Noise', 'Toxic', 'Unskilled', 'Unguarded machinery', 4, 'Artisan'),
('4', 'What are the three factors causes fire?', 'Fuel, Heat, Oxygen', 'Oxygen, Fuel, Nitrogen', 'Heat, Nitrogen, Oxygen', 'Fuel, Carbon-dioxide, Heat', 1, 'Artisan'),
('5', 'What “A” denotes in ABC of first aid?', 'Air way', 'Attention', 'Arresting', 'Atmosphere', 1, 'Artisan'),
('6', 'What is the reading of vernier caliper?', '30.20mm', '30.40mm', '35.20mm', '35.50mm', 4, 'Artisan'),
('7', 'What is the name of the part marked as X ?', 'Beam', 'Main scale', 'Fine adjusting nut', 'Fine adjusting slide', 4, 'Artisan'),
('8', '"Name the property of metal that withstand'),
('shock or impact?"', 'Tenacity', 'Hardness', 'Brittleness', 'Toughness', 4, 'Artisan'),
('9', 'In 5S concept SEISO means', 'Order', 'Arrangement', 'Clean', 'Sustain', 3, 'Artisan'),
('10', '_________ is a process of design applied to physical products that are to be manufactured by mass production', 'Industrial design', 'Product design', 'Customer design', 'Enterprise design', 1, 'Artisan'),
('11', 'In first angle projection, top view is always drawn _______________ the front view.', 'Left side', 'Above', 'Below', 'Right side', 3, 'Artisan'),
('12', 'Which of the following is safe conditions', 'Falling of Material', 'Slipping due to oil', 'Machine Working with Safe guards', 'Abnormal Sound/ Vibration', 3, 'Artisan'),
('13', 'Identify the First angle projection symbol', '', '', '', '', 1, 'Artisan'),
('14', 'What is an STL?', 'Initial pre-sliced file', 'The final sliced file', 'The type of filament', 'The coding program', 1, 'Artisan'),
('15', 'Which mechanical property of a metal offers resistance to elastic deformation in a cutting tool?', 'Ductility', 'Malleability', 'Hardness', 'Toughness', 3, 'Artisan'),
('16', '_________ is the permissible limit or limits of variation', 'Tolerance', 'Dimensioning', 'Measuring', 'Detailing', 1, 'Artisan'),
('17', 'Full form of GDNT is __________', 'Graphical Dimensioning and Tolerancing', 'Geometric Dimensioning and Tolerancing', 'Graphical Dimensioning and Toolpath', 'Good Dimensioning and Tolerancing', 2, 'Artisan'),
('18', ' _________is a quick, easy and direct form of creative brainstorming.', '5S', 'GD&T', 'SCAMPER', 'Simulation', 3, 'Artisan'),
('19', 'Identify the Flatness symbol from the following', '', '', '', '', 2, 'Artisan'),
('20', '"Toolbars and panels'),
('can be accessed from the'),
('_______ pull down menu"', 'File', 'Vector', 'Model', 'Window', 4, 'Artisan'),
('21', '__________ is the full form of CNC', 'Computer Numerical Control', 'Computer Number based Control system', 'Centralized Number Condition', 'Computer Nomenclature Condition', 1, 'Artisan'),
('22', '‘Ergonomics’ is related to human', 'Comfort', 'Safety', 'Comfort and Safety', 'Privacy', 3, 'Artisan'),
('23', 'The basic definition of Ergonomics is?', ' Using relaxed posture', ' Using stressed posture', 'Fitting the employee to the workstation', 'Fitting the workstation to the employee', 4, 'Artisan'),
('24', 'What is the type of the metal which contain iron?', 'Ferrous metals', 'Non-ferrous metals', 'Insulating metals', 'Non-Insulating             metals', 1, 'Artisan'),
('25', 'Which property of a metal enables it by which it can be drawn out into wires under tension without rupture?', 'Ductility', 'Malleability', 'Hardness', 'Brittleness', 1, 'Artisan'),
('26', 'Which one of the following properties is the mechanical properties of metal?', 'Fusibility', 'Ductility', 'Corrosion', 'Structure', 2, 'Artisan'),
('27', '_______ is the amount of time it takes to machine a complete product.', 'Normal Time', 'Total Time', 'Observed time', 'Machining cycle time', 4, 'Artisan'),
('28', 'A person who makes things skilfully, especially with his/her hands', 'Artisan', 'Craftsman', 'draftman', 'Gentleman', 1, 'Artisan'),
('29', 'which type of paint is used for metal painting?', 'Oil based paint', 'Water based paint', 'Cement Paint', 'Synthetic Rubber Paint', 1, 'Artisan'),
('30', 'Find out the isometric view tool from the following', '', '', '', '', 4, 'Artisan'),
('31', 'Identify the tool from following', 'Display material', 'Draw zero plane', 'Display bitmap', 'Material setup', 2, 'Artisan'),
('32', 'Toggle vector visibility is to', 'Toggle the 3D vector display', 'Toggle relief clipart display', 'Toggle display of front relief', 'Toggle display of back relief', 1, 'Artisan'),
('33', 'While creating 3D relief by using shape editor, vectors must be', 'Opened', 'Closed', 'Over lapped', 'Radially inward', 2, 'Artisan'),
('34', 'To use the Two rail sweep feature at least how many vectors must be required', 'One', 'Two', 'Three', 'Four', 3, 'Artisan'),
('35', 'Identify the icon from the following', 'Toggle visibility', 'Toggle display', 'Toggle', 'Hide', '1', 'Artisan'),
('36', 'Identify the type of Tool clearence strategy', 'Raster', 'Spiral', 'Spiral in box', 'Offset', '4', 'Artisan'),
('37', 'Following feature is used to', 'Create smart engraving tool path', 'Create drilling bank tool path', 'Create Drilling tool path', 'Create bevel carving tool path', '3', 'Artisan'),
('38', 'Which of the following mouse button is used for picking and selecting?', 'Left', 'Middle', 'Right', 'Left and Right', '1', 'Artisan'),
('39', 'Find the odd from the following', '', '', '', '', '4', 'Artisan'),
('40', 'Find the odd from the following', '', '', '', '', '3', 'Artisan'),
('41', 'Which of the following tool is used to create vector polyline/ curves?', '', '', '', '', '4', 'Artisan'),
('42', 'Find out the sculpture tool from the following', 'Smudge', 'Deposite', 'Weave', 'Carve', '3', 'Artisan'),
('43', 'Which of the following feature is used to scale,rotate and Shear the selected objects', 'Envelope distortion', 'Transform', 'Node editing', 'Block and rotate copy', '2', 'Artisan'),
('44', 'Find the odd from the following', '*.svg', '*.dxf', '*.rlf', '*.dgk', '3', 'Artisan'),
('45', 'Input of Laser cutting and engraving machine is_______', 'Vector', 'Relief', 'Tool path', 'Simulation', '1', 'Artisan'),
('46', 'Input of CNC machine is_________', 'Vector', 'Relief', 'Tool path', 'Simulation', '3', 'Artisan'),
('47', 'What is the unit of Feed rate?', 'mm/ft', 'mm', 'sec/inch', 'mm/sec', '4', 'Artisan'),
('48', 'Weld vectors is used to____', 'Join selected vectors with a line', 'Close selected vectors with lines', 'Weld selected vectors together', 'center vectors in a model', '3', 'Artisan'),
('49', 'Vector doctor is used to _________', 'Align centers in x of selected vectors', 'Align centers in y of selected vectors', 'Off set vectors', 'Identify and fix problems with vectors', '4', 'Artisan')
